### ISSUE TITLE
common sdk 版本不匹配，请确认 sdk初始化失败， 请检查是否集成umeng-asms-1.2x.aar

### ISSUE THREAD

**Issue by 164250072** [wangbo4020/flutter-plugins#2]
打release包，安装后启动时提示以下内容，获取不到deviceToken，    但是debug测试的时候没问题
“common sdk 版本不匹配，请确认
sdk初始化失败， 请检查是否集成umeng-asms-1.2x.aar”

**Comment by wangbo4020** [comment]
请问是否在主工程中也引入友盟相关的依赖？

**Comment by 164250072** [comment]
我将这个demo拉取下拉运行， 也提示这个问题。 测试手机是一款华为的百元机，使用flutter run --release运行的。
![7e78207ab944ba68ee0a38d15c69e0c](https://user-images.githubusercontent.com/23120717/124358548-67fd9380-dc53-11eb-9abb-8c5e0a93af7a.jpg)
![763538c88346a969a344571816f378b](https://user-images.githubusercontent.com/23120717/124358553-6c29b100-dc53-11eb-94af-f228321a32b1.jpg)

**Comment by 164250072** [comment]
不知道作者大大运行是否也有这个问题

**Comment by wangbo4020** [comment]
我检查一下，看看是不是最近升级了友盟后导致的。

**Comment by wangbo4020** [comment]
您好，我更新了Android端的友盟依赖仓库，Example在VivoZ3和OnePlusR7Pro上试了试，没有再出现该问题。
有空可以验证一下。
新版本是 **0.1.2**。
已发布到 pub.dev。

**Comment by wangbo4020** [comment]
今天改了个混淆的问题，已为插件增加混淆文件，重新 flutter pub upgrade 就好。版本 **0.1.3**

**Comment by 164250072** [comment]
> 今天改了个混淆的问题，已为插件增加混淆文件，重新 flutter pub upgrade 就好。版本 **0.1.3**

完美，已确认，没问题了

**Comment by wangbo4020** [comment]
> > 今天改了个混淆的问题，已为插件增加混淆文件，重新 flutter pub upgrade 就好。版本 **0.1.3**
> 
> 完美，已确认，没问题了

那我就关闭这个问题了。(*￣︶￣)
